ElectroShop/Areas/Admin/Controllers/DonHangController.cs
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Linq;
using System;
using System.Globalization;

namespace ElectroShop.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
		private dbElectroShopDataContext db = new dbElectroShopDataContext("Data Source=DESKTOP-33LF4EI\\SQLEXPRESS;Initial Catalog=ElectroShop;Integrated Security=True");
		// GET: Admin/Sach
		public ActionResult Index(int? page)
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			int iPageNum = (page ?? 1);
			int iPageSize = 7;
			return View(db.DONDATHANGs.ToList().OrderBy(n => n.MaDonHang).ToPagedList(iPageNum, iPageSize));
		}
		public ActionResult Details(int id)
		{
			var sach = db.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(sach);
		}
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var donHang = db.DONDATHANGs.SingleOrDefault(dh => dh.MaDonHang == id);

			if (donHang == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(donHang);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirm(int id)
		{
			var donHang = db.DONDATHANGs.SingleOrDefault(dh => dh.MaDonHang == id);

			if (donHang == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			// Retrieve all related CHITIETDATHANG records
			var chiTietDonHangs = db.CHITIETDATHANGs.Where(ct => ct.MaDonHang == id);

			// Delete each related CHITIETDATHANG record
			foreach (var chiTiet in chiTietDonHangs)
			{
				db.CHITIETDATHANGs.DeleteOnSubmit(chiTiet);
			}

			// Delete the DONDATHANG record
			db.DONDATHANGs.DeleteOnSubmit(donHang);

			db.SubmitChanges();

			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Edit(int id)
		{
			var donHang = db.DONDATHANGs.SingleOrDefault(dh => dh.MaDonHang == id);
			if (donHang == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(donHang);
		}

		[HttpPost]
		public ActionResult Edit(int id, FormCollection form)
		{
			var donHang = db.DONDATHANGs.SingleOrDefault(dh => dh.MaDonHang == id);
			if (donHang == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			if (ModelState.IsValid)
			{
				// Update order information
				donHang.DaThanhToan = bool.Parse(form["DaThanhToan"] == "true" ? "True" : "False");
				donHang.TinhTrangGiaoHang = int.Parse(form["TinhTrangGiaoHang"]);
				donHang.NgayGiao = DateTime.Parse(form["NgayGiao"]);
				// Save changes to the database
				db.SubmitChanges();

				// Redirect back to the order list or any other appropriate action
				return RedirectToAction("Index");
			}

			return View(donHang);
		}



	}
}

ElectroShop/Areas/Admin/Controllers/HangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace ElectroShop.Areas.Admin.Controllers
{
    public class HangController : Controller
    {
		private dbElectroShopDataContext db = new dbElectroShopDataContext("Data Source=DESKTOP-33LF4EI\\SQLEXPRESS;Initial Catalog=ElectroShop;Integrated Security=True");
		// GET: Admin/ChuDe
		public ActionResult Index(int? page)
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			int iPageNum = (page ?? 1);
			int iPageSize = 7;
			return View(db.HANGs.ToList().OrderBy(n => n.MaHang).ToPagedList(iPageNum, iPageSize));
		}
		[HttpGet]
		public ActionResult Create()
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			ViewBag.MaCD = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");
			return View();
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Create(HANG hang, FormCollection f, HttpPostedFileBase fFileUpLoad)
		{
			ViewBag.MaCD = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang");

			if (ModelState.IsValid)
			{
				// Kiểm tra xem TenChuDe đã tồn tại trong cơ sở dữ liệu hay chưa
				var existingChuDe = db.HANGs.FirstOrDefault(c => c.TenHang == hang.TenHang);

				if (existingChuDe != null)
				{
					ModelState.AddModelError("TenLoai", "Tên loại đã tồn tại");
					return View(hang);
				}
				else
				{
					// Nếu TenChuDe chưa tồn tại, thêm mới
					db.HANGs.InsertOnSubmit(hang);
					db.SubmitChanges();
					return RedirectToAction("Index");
				}
			}
			return View(hang);
		}
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var hang = db.HANGs.SingleOrDefault(n => n.MaHang == id);
			if (hang == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(hang);
		}
		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteComfirm(int id, FormCollection f)
		{
			var hang = db.HANGs.SingleOrDefault(n => n.MaHang == id);

			if (hang == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			var ctdh = db.SANPHAMs.Where(ct => ct.MaHang == id);
			if (ctdh.Count() > 0)
			{
				ViewBag.ThongBao = "Đang có sản phẩm thuộc hãng này!! <br>" + " Nếu muốn xóa thì phải xóa hết các sản phẩm thuộc hãng";
				return View(hang);
			}
			db.HANGs.DeleteOnSubmit(hang);
			db.SubmitChanges();
			return RedirectToAction("Index");
		}
	}
}

ElectroShop/Areas/Admin/Controllers/LoaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace ElectroShop.Areas.Admin.Controllers
{
    public class LoaiController : Controller
    {
		private dbElectroShopDataContext db = new dbElectroShopDataContext("Data Source=DESKTOP-33LF4EI\\SQLEXPRESS;Initial Catalog=ElectroShop;Integrated Security=True");
		// GET: Admin/ChuDe
		public ActionResult Index(int? page)
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			int iPageNum = (page ?? 1);
			int iPageSize = 7;
			return View(db.LOAISPs.ToList().OrderBy(n => n.MaLoai).ToPagedList(iPageNum, iPageSize));
		}
		[HttpGet]
		public ActionResult Create()
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			ViewBag.MaCD = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");
			return View();
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Create(LOAISP loai, FormCollection f, HttpPostedFileBase fFileUpLoad)
		{
			ViewBag.MaCD = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");

			if (ModelState.IsValid)
			{
				// Kiểm tra xem TenChuDe đã tồn tại trong cơ sở dữ liệu hay chưa
				var existingChuDe = db.LOAISPs.FirstOrDefault(c => c.TenLoai == loai.TenLoai);

				if (existingChuDe != null)
				{
					ModelState.AddModelError("TenLoai", "Tên loại đã tồn tại");
					return View(loai);
				}
				else
				{
					// Nếu TenChuDe chưa tồn tại, thêm mới
					db.LOAISPs.InsertOnSubmit(loai);
					db.SubmitChanges();
					return RedirectToAction("Index");
				}
			}
			return View(loai);
		}
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var loai = db.LOAISPs.SingleOrDefault(n => n.MaLoai == id);
			if (loai == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(loai);
		}
		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteComfirm(int id, FormCollection f)
		{
			var loai = db.LOAISPs.SingleOrDefault(n => n.MaLoai == id);

			if (loai == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			var ctdh = db.SANPHAMs.Where(ct => ct.MaLoai == id);
			if (ctdh.Count() > 0)
			{
				ViewBag.ThongBao = "Đang có sản phẩm thuộc loại này!! <br>" + " Nếu muốn xóa thì phải xóa hết các sản phẩm thuộc loại này";
				return View(loai);
			}
			db.LOAISPs.DeleteOnSubmit(loai);
			db.SubmitChanges();
			return RedirectToAction("Index");
		}
	}
}

ElectroShop/Areas/Admin/Controllers/SanPhamController.cs
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Linq;
using System;

namespace ElectroShop.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
		private dbElectroShopDataContext db = new dbElectroShopDataContext("Data Source=DESKTOP-33LF4EI\\SQLEXPRESS;Initial Catalog=ElectroShop;Integrated Security=True");
		// GET: Admin/Sach
		public ActionResult Index(int? page)
		{
			if (Session["Admin"] == null)
			{
				return RedirectToAction("Login", "Admin");
			}
			int iPageNum = (page ?? 1);
			int iPageSize = 7;
			return View(db.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(iPageNum, iPageSize));
		}
		[HttpGet]
		public ActionResult Create()
		{
			ViewBag.MaHang = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang");
			ViewBag.MaLoai = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");
			return View();
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Create(SANPHAM sp, FormCollection f, HttpPostedFileBase fFileUpLoad)
		{
			//Đưa dữ liệu vào DropDown
			ViewBag.MaLoai = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai");
			ViewBag.MaHang = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang");
			if (fFileUpLoad == null)
			{
				//Nội dung thông báo yêu cầu chọn ảnh bìa
				ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
				//Lưu thông tin để khi load lại trang do yêu cầu chọn ảnh bìa sẽ hiển thị các thông tin này lên trang
				ViewBag.TenSach = f["sTenSP"];
				ViewBag.MoTa = f["sMoTa"];
				ViewBag.SoLuong = int.Parse(f["iSoLuong"]);
				ViewBag.GiaBan = decimal.Parse(f["mGiaBan"]);
				ViewBag.MaHang = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang", int.Parse(f["MaHang"]));
				ViewBag.MaLoai = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai", int.Parse(f["MaLoai"]));
				return View();
			}
			else
			{
				if (ModelState.IsValid)
				{
					//Lấy tên file (Khai báo thư viện: System.IO)
					var sFileName = Path.GetFileName(fFileUpLoad.FileName);
					//Lấy đường dẫn lưu file
					var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
					//Kiểm tra ảnh bìa đã tồn tại chưa để lưu lên thư mục
					if (!System.IO.File.Exists(path))
					{
						fFileUpLoad.SaveAs(path);
					}
					//Lưu Sach vào CSDL
					sp.TenSP = f["sTenSP"];
					sp.MoTa = f["sMota"];
					sp.AnhBia = sFileName;
					sp.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);
					sp.SoLuongBan = int.Parse(f["iSoLuong"]);
					sp.GiaBan = decimal.Parse(f["mGiaBan"]);
					sp.MaHang = int.Parse(f["MaHang"]);
					sp.MaLoai = int.Parse(f["MaLoai"]);
					db.SANPHAMs.InsertOnSubmit(sp);
					db.SubmitChanges();
					return RedirectToAction("Index");
				}
				return View();
			}
		}
		public ActionResult Details(int id)
		{
			var sach = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(sach);
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var sp = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(sp);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteComfirm(int id, FormCollection f)
		{
			var sp = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);

			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			var ctdh = db.CHITIETDATHANGs.Where(ct => ct.MaSP == id);
			if (ctdh.Count() > 0)
			{
				//Nội dung sẽ hiển thị khi sách cần xóa đã có trong table ChiTietDonHang
				ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng <br>" + " Nếu muốn xóa thì phải xóa hết mã sách này trong bảng Chi tiết đặt hàng";
				return View(sp);
			}
			//Xóa sách
			db.SANPHAMs.DeleteOnSubmit(sp);
			db.SubmitChanges();
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var sp = db.SANPHAMs.SingleOrDefault(n => n.MaSP == id);
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			ViewBag.MaLoai = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai", sp.MaLoai);
			ViewBag.MaHang = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang", sp.MaHang);
			return View(sp);
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
		{
			if (f == null)
			{
				// Handle the case where FormCollection is null
				return RedirectToAction("Index");
			}

			var iMaSP = f["iMaSP"];
			if (iMaSP == null)
			{
				// Handle the case where iMaSP is null
				return RedirectToAction("Index");
			}

			var sp = db.SANPHAMs.SingleOrDefault(n => n.MaSP == int.Parse(iMaSP));
			if (sp == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			ViewBag.MaLoai = new SelectList(db.LOAISPs.ToList().OrderBy(n => n.TenLoai), "MaLoai", "TenLoai", sp.MaLoai);
			ViewBag.MaHang = new SelectList(db.HANGs.ToList().OrderBy(n => n.TenHang), "MaHang", "TenHang", sp.MaHang);

			if (ModelState.IsValid)
			{
				if (fFileUpload != null && !string.IsNullOrEmpty(fFileUpload.FileName))
				{
					var sFileName = Path.GetFileName(fFileUpload.FileName);
					var path = Path.Combine(Server.MapPath("~/Images"), sFileName);

					if (!System.IO.File.Exists(path))
					{
						fFileUpload.SaveAs(path);
					}
					sp.AnhBia = sFileName;
				}

				sp.TenSP = f["sTenSP"];
				sp.MoTa = f["sMoTa"];
				sp.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);
				sp.SoLuongBan = int.Parse(f["iSoLuong"]);
				sp.GiaBan = decimal.Parse(f["mGiaBan"]);
				sp.MaLoai = int.Parse(f["MaLoai"]);
				sp.MaHang = int.Parse(f["MaHang"]);

				db.SubmitChanges();
				return RedirectToAction("Index");
			}

			return View(sp);
		}

	}
}

ElectroShop/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@using ElectroShop.Models
@using ADMIN = ElectroShop.Models.ADMIN

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <title>@ViewBag.Title</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/Scripts/bootstrap.min.css" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/Scripts/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/Scripts/slick-theme.css" />

    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/Scripts/nouislider.min.css" />

    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/Scripts/font-awesome.min.css">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Scripts/style.css" />
    <style>
        .cart-link,
        .card-link {
            font-weight: bold;
            text-decoration: none;
            color: white; /* Set the color to white */
            display: flex;
            align-items: center;
        }

            .cart-link i {
                margin-right: 5px; /* Adjust the margin as needed */
            }
    </style>
    <style>
        .custom-nav {
            background-color: #333; /* Set a dark background color for the navigation */
            text-align: center; /* Center-align the navigation items */
            padding: 10px 0; /* Add padding to the navigation bar */
        }

            .custom-nav ul {
                list-style: none; /* Remove default list styles */
                padding: 0;
                margin: 0;
                display: flex; /* Display list items horizontally */
                justify-content: center; /* Center-align list items horizontally */
            }

            .custom-nav li {
                margin: 0 10px; /* Add margin between list items */
            }

            .custom-nav a {
                font-weight: bold;
                text-decoration: none;
                color: white; /* Set text color to white */
                display: flex;
                align-items: center;
                padding: 10px;
            }

                .custom-nav a:hover {
                    border-bottom: 2px solid white; /* Add a white underline on hover */
                }
    </style>


</head>
<body>
    <header>
        <div id="top-header">
            <div class="container">
            </div>
            <div id="header">
                <!-- container -->
                <div class="container">
                    <!-- row -->
                    <div class="row">
                        <!-- LOGO -->
                        <div class="col-md-3">
                            <div class="header-logo">
                                <a href="@Url.Action("Index", "Admin")" class="logo">
                                    <img src="~/Images/logo.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-md-5">

                        </div>
                        <div class="col-md-4">
                            <div class="header-ctn">
                                <!-- Wishlist -->
                                <div>
                                    <ul>
                                        <li>
                                            @if (Session["Admin"] is ElectroShop.Models.ADMIN admin && admin != null)
                                            {
                                                <a href="#" class="card-link">
                                                    <span class="glyphicon glyphicon-user"></span>
                                                    Xin chào: @admin.HoTen
                                                </a>
                                            }
                                        </li>
                                        <li>
                                            <a href="@Url.Action("Logout", "Admin")" class="cart-link">
                                                <span class="glyphicon glyphicon-log-out"></span>
                                                Đăng xuất
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <!-- /ACCOUNT -->
                    </div>
                    <!-- row -->
                </div>
                <!-- container -->
            </div>
        </div>
    </header>

    <nav class="custom-nav">
        <!-- container -->
        <div class="container">
            <!-- responsive-nav -->
            <div>
                <ul>
                    <li>
                        <a href="@Url.Action("Index","SanPham")">QUẢN LÝ SẢN PHẨM</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Hang")">QUẢN LÝ HÃNG</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Loai")">QUẢN LÝ LOẠI SẢN PHẨM</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","DonHang")">QUẢN LÝ ĐƠN HÀNG</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /container -->
    </nav>

    <div class="container">
        <p></p>
    </div>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>