ElectroShop/Controllers/ElectroShopController.cs
using System;
using System.Collections.Generic;
using System.Configuration.Provider;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;
using System.Web.UI;
using PagedList;
using PagedList.Mvc;
using System.Drawing.Printing;


namespace ElectroShop.Controllers
{
    public class ElectroShopController : Controller
    {
		private string connection;
		private dbElectroShopDataContext data;

		public ElectroShopController()
		{
			// Khởi tạo chuỗi kết nối
			connection = "Data Source=DESKTOP-33LF4EI\\SQLEXPRESS;Initial Catalog=ElectroShop;Integrated Security=True";
			data = new dbElectroShopDataContext(connection);
		}

		private List<SANPHAM> LaySanPham(int count)
		{
			return data.SANPHAMs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
		}
		// GET: ElectroShop
		public ActionResult Index(int? page)
        {
			int pageSize = 6;
			int pageNumber = (page ?? 1);

			var listSanPham = LaySanPham(500);
			return View(listSanPham.ToPagedList(pageNumber, pageSize));
		}
		public ActionResult SanPhamBanNhieuPartial()
		{
			var listSanPhamBanNhieu = data.SANPHAMs.OrderByDescending(a => a.SoLuongBan).Take(6).ToList();

			return PartialView("SanPhamBanNhieuPartial", listSanPhamBanNhieu);
		}
		public ActionResult SapXep()
		{
			return PartialView("SapXepPartial");
		}
		private List<SANPHAM> LaySanPhamTheoGiaTangDan(int count)
		{
			return data.SANPHAMs.OrderBy(a => a.GiaBan).Take(count).ToList();
		}
		public ActionResult SanPhamTangDan(int? page)
		{
			int pageSize = 6;
			int pageNumber = (page ?? 1);

			var listSanPhamTangDan = LaySanPhamTheoGiaTangDan(500);

			return View(listSanPhamTangDan.ToPagedList(pageNumber, pageSize));
		}
		private List<SANPHAM> LaySanPhamTheoGiaGiamDan(int count)
		{
			return data.SANPHAMs.OrderByDescending(a => a.GiaBan).Take(count).ToList();
		}
		public ActionResult SanPhamGiamDan(int? page)
		{
			int pageSize = 6;
			int pageNumber = (page ?? 1);

			var listSanPhamGiamDan = LaySanPhamTheoGiaGiamDan(500);

			return View(listSanPhamGiamDan.ToPagedList(pageNumber, pageSize));
		}
		public ActionResult LoaiSPPartial()
		{
			var listloaiSP = from lsp in data.LOAISPs select lsp;
			return PartialView(listloaiSP);
		}
		private string LayLoaiSP(int id)
		{
			var chuDe = data.LOAISPs.SingleOrDefault(cd => cd.MaLoai == id);

			if (chuDe != null)
			{
				return chuDe.TenLoai;
			}

			return "Không tìm thấy chủ đề";
		}
		public ActionResult SanPhamTheoLoai(int id, int? page)
		{
			int pageSize = 3;
			int pageNumber = page ?? 1;

			var sp = data.SANPHAMs.Where(s => s.MaLoai == id)
								  .OrderByDescending(s => s.NgayCapNhat)
								  .ToPagedList(pageNumber, pageSize);

			ViewBag.Id = id;
			ViewBag.ten = LayLoaiSP(id);

			return View(sp);
		}
		public ActionResult HangPartial()
		{
			var listhang = from h in data.HANGs select h;
			return PartialView(listhang);
		}
		private string LayHang(int id)
		{
			var chuDe = data.HANGs.SingleOrDefault(cd => cd.MaHang == id);

			if (chuDe != null)
			{
				return chuDe.TenHang;
			}

			return "Không tìm thấy chủ đề";
		}
		public ActionResult SanPhamTheoHang(int id, int? page)
		{
			int pageSize = 3;
			int pageNumber = page ?? 1;

			var sp = data.SANPHAMs.Where(s => s.MaHang == id)
								  .OrderByDescending(s => s.NgayCapNhat)
								  .ToPagedList(pageNumber, pageSize);

			ViewBag.Id = id;
			ViewBag.ten = LayHang(id);

			return View(sp);
		}
		public ActionResult ChiTietSP(int id)
		{
			var sach = from s in data.SANPHAMs
					   where s.MaSP == id
					   select s;
			return View(sach.Single());
		}
		public ActionResult LoginLogout()
		{
			return PartialView("LoginLogoutPartial");
		}
		public ActionResult TimKiemSanPham(string keyword, int? page)
		{
			// Check if the keyword is provided
			if (string.IsNullOrEmpty(keyword))
			{
				// Handle the case where no keyword is provided (you can redirect to the home page or show an error message)
				return RedirectToAction("Index");
			}

			int pageSize = 3;
			int pageNumber = page ?? 1;

			// Perform the search based on the product name
			var searchResults = data.SANPHAMs
									.Where(s => s.TenSP.Contains(keyword))
									.OrderByDescending(s => s.NgayCapNhat)
									.ToPagedList(pageNumber, pageSize);

			ViewBag.Keyword = keyword; // Pass the keyword to the view

			return View(searchResults);
		}
	}
}

ElectroShop/Views/ElectroShop/ChiTietSP.cshtml

@{
    ViewBag.Title = "ChiTietSP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .tensp {
        text-align: center;
        font-family: Tahoma;
        font-size: 22px;
        font-weight: bolder;
        text-transform: uppercase;
        height: 30px;
        padding: 25px 0px 50px 0px;
    }

    .anh {
        width: 350px;
        padding: 0px 20px;
    }

    .motasp {
        text-align: justify;
        margin-top: 20px;
        padding-right: 50px;
        font-size: 15px;
    }

    .khoiA {
        margin-left: 600px;
        font-size: 15px;
    }
</style>
<div class="thumbnail" style="height:auto;">
    <h4 class="tensp">@Model.TenSP</h4>
    <img style="height:400px;" class="anh" src="~/Images/@Model.AnhBia" alt="@Model.TenSP" />
    <div>
        <p class="motasp">
            @Html.Raw(Model.MoTa.ToString().Replace("\n", "</p><p>/&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </p>
    </div>

    <div class="khoiA">
        <p class="ngaycapnhat"><b>Ngày cập nhật:</b> <i>@Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}")</i></p>
        <p class="giaban"><b>Giá bán:</b> <span style="color: #D10024; font-size: 25px; font-family: Tahoma; font-style: italic; font-weight: 800;">@Html.FormatValue(@Model.GiaBan, "{0:#,##0}")VNĐ</span></p>
        <p>
            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = Model.MaSP, url =Request.Url.ToString() }) " class="btn btn-primary1" role="button">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
            </a>
        </p>
    </div>
</div>
<style>
    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
</style>

ElectroShop/Views/ElectroShop/HangPartial.cshtml
    @model IEnumerable<ElectroShop.Models.HANG>
    <ul class="main-nav nav navbar-nav">
        <li class="active"><a href="@Url.Action("Index", "ElectroShop")">Trang chủ</a></li>
        @foreach (var item in Model)
        {
            <li>
                <a href="@Url.Action("SanPhamTheoHang","ElectroShop", new {id = item.MaHang})">@item.TenHang</a>
            </li>
        }
    </ul>


ElectroShop/Views/ElectroShop/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ElectroShop.Models.SANPHAM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
        public string Abbreviate(string input, int maxLength)
        {
            if (input.Length <= maxLength)
            {
                return input;
            }
            else
            {
                return input.Substring(0, maxLength) + "...";
            }
        }
    }
</script>
<nav>
    <!-- container -->
    <div>
        <!-- responsive-nav -->
        <div>
            <!-- NAV -->
            <div class="slider">
                <div class="list">
                    <div class="item">
                        <img src="~/Images/DGHelp_Banner_2000X650_acer.jpg" alt="">
                    </div>
                    <div class="item">
                        <img src="~/Images/z4953726235718_f6add0fc5ef9fe509b3eb19810341009.jpg" alt="">
                    </div>
                </div>
                <div class="buttons">
                    <button id="prev"><</button>
                    <button id="next">></button>
                </div>
                <ul class="dots">
                    <li class="active"></li>
                    <li></li>
                </ul>
            </div>
            <select class="input-select" onchange="window.location.href=this.value">
                <option value="0">Sắp xếp theo giá</option>
                @Html.Action("SapXep", "ElectroShop")
            </select>
            <!-- /NAV -->
        </div>
    </div>
    <!-- /container -->
</nav>
<div class="row text-center">
    @foreach (var sp in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
            <div class="thumbnail">
                <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                    </h4>
                    <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
        {
            Display = PagedListDisplayMode.IfNeeded
        })
    </div>
</div>

<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }

    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
</style>


ElectroShop/Views/ElectroShop/LoaiSPPartial.cshtml
@model IEnumerable<ElectroShop.Models.LOAISP>
@foreach (var item in Model)
{
    <option value="@Url.Action("SanPhamTheoLoai", "ElectroShop", new { id = item.MaLoai })">@item.TenLoai</option>
}

ElectroShop/Views/ElectroShop/SanPhamBanNhieuPartial.cshtml

@model IEnumerable<ElectroShop.Models.SANPHAM>

<hr>
<h2 class="text-center">SẢN PHẨM ĐƯỢC MUA NHIỀU NHẤT</h2>
<hr>

<div class="book-slider-container">
    <button class="slider-button prev-button" id="prevButton"><i class="fa-solid fa-chevron-left"></i></button>
    <button class="slider-button next-button" id="nextButton"><i class="fa-solid fa-chevron-right"></i></button>
    <div class="book-slider">
        @foreach (var sp in Model)
        {
            <div class="book-slide">
                <div class="thumbnail">
                    <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                    <div class="caption">
                        <h4 class="ten">
                            <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                        </h4>
                        <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                        <p>
                            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<style>
    .book-slider-container {
        overflow: hidden;
        position: center;
        width: 100%;
    }

    .book-slider {
        display: flex;
        overflow-x: hidden;
        scroll-behavior: unset;
    }

    .book-slide {
        flex: 0 0 33.3333%; /* Chia 3 cột cho mỗi slide */
        padding: 10px;
        /* Thêm kiểu dáng và khoảng cách cho từng cuốn sách */
    }

    .prev-button,
    .next-button {
        background-color: #fff;
        color: #000000;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
    }

    .prev-button {
        float: left;
    }

    .next-button {
        float: right;
    }

    .slider-button {
        height: 540px;
    }

    .caption {
        text-align: center;
    }

</style>
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }

    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var slider = $(".book-slider");
        var slideWidth = $(".book-slide").outerWidth();
        var scrollAmount = slideWidth * 1; // Di chuyển 1 cuốn sách mỗi lần

        $("#nextButton").click(function () {
            slider.animate({ scrollLeft: "+=" + scrollAmount }, 500);
        });

        $("#prevButton").click(function () {
            slider.animate({ scrollLeft: "-=" + scrollAmount }, 500);
        });
    });
    @functions {
    public string Abbreviate(string input, int maxLength)
    {
        if (input.Length <= maxLength)
        {
            return input;
        }
        else
        {
            return input.Substring(0, maxLength) + "...";
        }
    }
}
</script>


ElectroShop/Views/ElectroShop/SanPhamGiamDan.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ElectroShop.Models.SANPHAM>
@{
    ViewBag.Title = "SanPhamGiamDan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
        public string Abbreviate(string input, int maxLength)
        {
            if (input.Length <= maxLength)
            {
                return input;
            }
            else
            {
                return input.Substring(0, maxLength) + "...";
            }
        }
    }
</script>
<nav>
    <!-- container -->
    <div>
        <!-- responsive-nav -->
        <div>
            <!-- NAV -->
            <div class="slider">
                <div class="list">
                    <div class="item">
                        <img src="~/Images/DGHelp_Banner_2000X650_acer.jpg" alt="">
                    </div>
                    <div class="item">
                        <img src="~/Images/z4953726235718_f6add0fc5ef9fe509b3eb19810341009.jpg" alt="">
                    </div>
                </div>
                <div class="buttons">
                    <button id="prev"><</button>
                    <button id="next">></button>
                </div>
                <ul class="dots">
                    <li class="active"></li>
                    <li></li>
                </ul>
            </div>
            <select class="input-select" onchange="window.location.href=this.value">
                <option value="0">Sắp xếp theo giá</option>
                @Html.Action("SapXep", "ElectroShop")
            </select>
            <!-- /NAV -->
        </div>
    </div>
    <!-- /container -->
</nav>
<div class="row text-center">
    @foreach (var sp in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
            <div class="thumbnail">
                <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                    </h4>
                    <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("SanPhamGiamDan", new { page }), new PagedListRenderOptions
        {
            Display = PagedListDisplayMode.IfNeeded
        })
    </div>
</div>

<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }

    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
    .slider-container {
        display: flex;
        width: 300%; /* Số ảnh nhân với 100% để tạo hiệu ứng chuyển động */
        transition: transform 5s ease; /* Thời gian và kiểu chuyển động */
    }

    .slider-image {
        margin-right: 160px; /* Thêm khoảng cách giữa các ảnh */
    }
</style>


ElectroShop/Views/ElectroShop/SanPhamTangDan.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ElectroShop.Models.SANPHAM>
@{
    ViewBag.Title = "SanPhamTangDan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
        public string Abbreviate(string input, int maxLength)
        {
            if (input.Length <= maxLength)
            {
                return input;
            }
            else
            {
                return input.Substring(0, maxLength) + "...";
            }
        }
    }
</script>
<nav>
    <!-- container -->
    <div>
        <!-- responsive-nav -->
        <div>
            <!-- NAV -->
            <div class="slider">
                <div class="list">
                    <div class="item">
                        <img src="~/Images/DGHelp_Banner_2000X650_acer.jpg" alt="">
                    </div>
                    <div class="item">
                        <img src="~/Images/z4953726235718_f6add0fc5ef9fe509b3eb19810341009.jpg" alt="">
                    </div>
                </div>
                <div class="buttons">
                    <button id="prev"><</button>
                    <button id="next">></button>
                </div>
                <ul class="dots">
                    <li class="active"></li>
                    <li></li>
                </ul>
            </div>
            <select class="input-select" onchange="window.location.href=this.value">
                <option value="0">Sắp xếp theo giá</option>
                @Html.Action("SapXep", "ElectroShop")
            </select>
            <!-- /NAV -->
        </div>
    </div>
    <!-- /container -->
</nav>
<div class="row text-center">
    @foreach (var sp in Model)
    {
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
            <div class="thumbnail">
                <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                <div class="caption">
                    <h4 class="ten">
                        <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                    </h4>
                    <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                    <p>
                        <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                        </a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<div class="text-center">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("SanPhamTangDan", new { page }), new PagedListRenderOptions
        {
            Display = PagedListDisplayMode.IfNeeded
        })
    </div>
</div>

<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }

    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
    .slider-container {
        display: flex;
        width: 300%; /* Số ảnh nhân với 100% để tạo hiệu ứng chuyển động */
        transition: transform 5s ease; /* Thời gian và kiểu chuyển động */
    }

    .slider-image {
        margin-right: 160px; /* Thêm khoảng cách giữa các ảnh */
    }
</style>


ElectroShop/Views/ElectroShop/SanPhamTheoHang.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ElectroShop.Models.SANPHAM>
@{
    ViewBag.Title = "SanPhamTheoHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
    public string Abbreviate(string input, int maxLength)
    {
        if (input.Length <= maxLength)
        {
            return input;
        }
        else
        {
            return input.Substring(0, maxLength) + "...";
        }
    }
}
</script>
@if (Model.Any())
{
    <hr />
    <h2 class="text-center">Sản phẩm theo hãng @ViewBag.ten</h2>
    <hr />
    <div class="row text-center">
        @foreach (var sp in Model)
        {
            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
                <div class="thumbnail">
                    <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                    <div class="caption">
                        <h4 class="ten">
                            <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                        </h4>
                        <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                        <p>
                            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="text-center">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("SanPhamTheoHang", new { page }), new PagedListRenderOptions
            {
                Display = PagedListDisplayMode.IfNeeded
            })
        </div>
    </div>
}
else
{
    <p class="text-center">Không có sản phẩm nào cho hãng này.</p>
}
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
</style>

ElectroShop/Views/ElectroShop/SanPhamTheoLoai.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ElectroShop.Models.SANPHAM>
@{
    ViewBag.Title = "SanPhamTheoLoai";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
    public string Abbreviate(string input, int maxLength)
    {
        if (input.Length <= maxLength)
        {
            return input;
        }
        else
        {
            return input.Substring(0, maxLength) + "...";
        }
    }
}
</script>
@if (Model.Any())
{
    <hr />
    <h2 class="text-center">Sản phẩm theo loại @ViewBag.ten</h2>
    <hr />
    <div class="row text-center">
        @foreach (var sp in Model)
        {
            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
                <div class="thumbnail">
                    <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                    <div class="caption">
                        <h4 class="ten">
                            <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                        </h4>
                        <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                        <p>
                            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="text-center">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("SanPhamTheoLoai", new { page }), new PagedListRenderOptions
            {
                Display = PagedListDisplayMode.IfNeeded
            })
        </div>
    </div>
}
else
{
    <p class="text-center">Không có sản phẩm nào cho hãng này.</p>
}
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }

</style>

ElectroShop/Views/ElectroShop/SapXepPartial.cshtml
@using ElectroShop.Models
<option value="@Url.Action("SanPhamTangDan", "ElectroShop")">Tăng dần</option>
<option value="@Url.Action("SanPhamGiamDan", "ElectroShop")">Giảm dần</option>

ElectroShop/Views/ElectroShop/TimKiemSanPham.cshtml
@model PagedList.IPagedList<ElectroShop.Models.SANPHAM>
@using PagedList.Mvc;
@{
    ViewBag.Title = "TimKiemSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    @functions {
    public string Abbreviate(string input, int maxLength)
    {
        if (input.Length <= maxLength)
        {
            return input;
        }
        else
        {
            return input.Substring(0, maxLength) + "...";
        }
    }
}
</script>
<h2 style="text-align: center">Kết quả tìm kiếm cho "@ViewBag.Keyword"</h2>

@if (Model.Any())
{
    <div class="row text-center">
        @foreach (var sp in Model)
        {
            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-7 sp">
                <div class="thumbnail">
                    <img src="~/Images/@sp.AnhBia" alt="Thumbnail Image 1" class="img-responsive img-rounded imgbook">
                    <div class="caption">
                        <h4 class="ten">
                            <a href="@Url.Action("ChiTietSP", "ElectroShop", new { id = sp.MaSP })">@Abbreviate(sp.TenSP, 20)</a>
                        </h4>
                        <h4>@string.Format("{0:N0}VNĐ", sp.GiaBan)</h4>
                        <p>
                            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary1" role="button">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>Add to Cart
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>

    <!-- Pagination -->
    <div class="text-center">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("TimKiemSanPham", new { page, keyword = ViewBag.Keyword }))
    </div>
}
else
{
    <p>Không tìm thấy kết quả nào.</p>
}
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }

    .btn-primary1 {
        color: #fff;
        background-color: #D10024;
        border-color: #D10024;
    }
</style>